# CONFIG YAML - Medium - Block Size 4 - Clusters 8
experiment_metadata:
  experiment_name: "RD Clustering - Medium - B4 C8"
  experiment_code: "RD-Medium-B4-C8"
  experiment_date: "2025-12-07"
  experiment_info: "Medium complexity execution for RD Clustering with block size 4 and 8 clusters"
  export_folder: "results/PCADC_TEST"
  temp_folder: "results/temp"

pointcloud_metadata:
  point_cloud_dataset: "8iVFB v2"
  point_cloud_sequence: "longdress"
  point_cloud_depth: 10
  point_cloud_frame: 1051

sequential_params:
  point_cloud_path: "res/longdress_vox10_1051.ply"
  normalize_slopes: True
  decider_mode: 0
  self_loop_weight: 1.6
  self_loop_threshold: 0.7
  quantization_steps: [24, 32, 48, 64]
  lagrange_proportional: 0.8
  block_size: 4

clustering_params:
  number_of_clusters: 8
  max_iterations: 50
  min_iterations: 2
  rd_cost_threshold: 0.05
  iteration_window: 2
  initial_temperature: 1.0
  final_temperature: 0.1
  cooling_rate: 0.8
  learning_rate: 0.5

rewrite_results: False
debugging: False
