# experiment_config.yaml
experiment_name: "Test Experiment"
experiment_code: "BE01"
experiment_date: "2025-05-01"
experiment_info: "Different Weight"

# File and paths
point_cloud_path:
  - res/longdress_vox10_1051.ply


rewrite_results: False
debugging: True
export_folder: /media/simao/TOSHIBA EXT/Experiments

# Method parameters
self_loop_weight:
  - 0.8
  - 0.4
  - 1.6
  -

self_loop_percentage:
  - 0.05
  - 0.1
  - 0.2
  - 0.3


# Encoding ranges parameters
quantization_steps:
  - 24
  - 28
  - 32
  - 40
  - 48
  - 56
  - 64

block_size:
  - 4